import Head from 'next/head'
import styles from '@/styles/Main.module.scss'
import DrawerAppBar from '@/components/DrawerAppBar'
import Description from '@/components/Description'
import Examples from '@/components/Examples'



export default function Home() {
  return (
    <>
      <Head>
        <title>3D-PRINT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <DrawerAppBar />
        <Description />
        <Examples />
      </main>
    </>
  )
}
