import Head from 'next/head'
import Examples from '@/components/Examples'
import Benefits from '@/components/Benefits'
import Working from '@/components/Working'
import Price from '@/components/Price'
import Form from '@/components/Form'
import Footer from '@/components/Footer'
import { ThemeProvider } from '@mui/material/styles';
import theme from '@/styles/theme'
import Introduction from '@/components/Introduction'
import Header from '@/components/Header'


export default function Home() {
  return (
    <>
      <Head>
        <title>3D-PRINT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link rel="stylesheet" href="../fonts/Montserrat-Regular.ttf"
          as="font"
          crossOrigin="" />
        <link rel="stylesheet" href="../fonts/Montserrat-Medium.ttf"
          as="font"
          crossOrigin="" />
        <link rel="stylesheet" href="../fonts/Montserrat-SemiBold.ttf"
          as="font"
          crossOrigin="" />
        <link rel="stylesheet" href="../fonts/Montserrat-Bold.ttf"
          as="font"
          crossOrigin="" /> */}
      </Head>
      <main >
        <ThemeProvider theme={theme}>
          <Header />
          <Introduction />
          <Examples />
          <Benefits />
          <Working />
          <Price />
          <Form />
          <Footer />
        </ThemeProvider>
      </main>
    </>
  )
}
